server:
  port: 8789

spring:
  application:
    name: max-service
  datasource:
    username: ushirik-educ
    url: jdbc:postgresql://localhost:5432/student_max
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true



    #Kafka configuration
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    topics: create-student, create-parent

#    consumer:
#      enable-auto-commit: true
#      bootstrap-servers: localhost:9092
#      group-id: class-work
#      auto-offset-reset: earliest
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*'
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#      topics:
#        name: create-classwork;

