server:
  port: 8083

spring:
  application:
    name: school-service
  datasource:
    username: ushirik-educ
    url: jdbc:postgresql://localhost:5432/Students
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true